# Generated by Django 3.0 on 2024-11-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='logintable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='signuptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='packagemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=10000)),
                ('photo', models.CharField(max_length=400)),
                ('PLOG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventteam')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10000)),
                ('FDLOG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.logintable')),
            ],
        ),
        migrations.AddField(
            model_name='eventteam',
            name='EVLOG',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.logintable'),
        ),
        migrations.CreateModel(
            name='cmplnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=1000)),
                ('re', models.CharField(max_length=1000)),
                ('CLOG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('estimate', models.CharField(default='', max_length=100)),
                ('ALOG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.packagemodel')),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.signuptable')),
            ],
        ),
    ]
