# Generated by Django 3.0 on 2024-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptable',
            name='portfolio',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
