# Generated by Django 3.0 on 2024-12-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_signuptable_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuptable',
            name='portfolio',
        ),
    ]
