# Generated by Django 3.0 on 2025-01-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_signuptable_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_date', models.CharField(max_length=500)),
                ('amnt', models.CharField(max_length=500)),
                ('p_status', models.CharField(max_length=500)),
                ('REQ_MAIN_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.appointments')),
            ],
        ),
    ]
