# Generated by Django 3.0 on 2025-01-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='REQ_MAIN_id',
        ),
        migrations.AddField(
            model_name='payments',
            name='REQ_MAIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.appointments'),
        ),
    ]
