# Generated by Django 3.0 on 2025-01-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20250106_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptable',
            name='portfolio',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
