# Generated by Django 3.0 on 2025-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20250111_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='photo1',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='photo2',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='photo3',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='photo4',
            field=models.CharField(default='', max_length=400),
        ),
    ]
