# Generated by Django 3.0 on 2025-03-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20250321_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagemodel',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.DeleteModel(
            name='eventteam',
        ),
    ]
