# Generated by Django 3.0 on 2025-03-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20250321_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='crowd',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='details',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
